allowBuilds:
  '@parcel/watcher': false
  '@prisma/client': true
  '@prisma/engines': true
  '@tailwindcss/oxide': false
  bcrypt: false
  esbuild: false
  msgpackr-extract: false
  prisma: true
  unrs-resolver: false
  vue-demi: false
  workerd: false
